# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: packages/seatmaps-client

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          scope: "@aisaac-lab"

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Dependencies Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
