# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish GitHub Packages

on: workflow_dispatch

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: "@aisaac-lab"
      - run: cd packages/seatmaps-client && pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
