name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          scope: "@aisaac-lab"

      - name: Dependencies Install
        run: pnpm install

      - name: Build
        run: cd packages/seatmaps-client && pnpm build:esm

      - name: Publish package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
